### PR TITLE
fix: could not find module in rave.bvn.js

### PR DESCRIPTION
**Pull request by FeezyHendrix**
completed require statement to point to correct file.

### CODE REVIEW

**Comment by Corvus97** [comment]
Hello @FeezyHendrix,

Thanks for your interest in contributing to our Repo.

Kindly resolve the conflict in the pull request to enable us review and merge your commits.

Keep being Awesome.

Corvus.

**Comment by FeezyHendrix** [comment]
Hi @Corvus97,
Resolved the conflict.
Thanks.

**Comment by Corvus97** [comment]
@Olufemiobafunmiso kindly review PR and approve for merging.

**Comment by Corvus97** [comment]
Dear @FeezyHendrix,

Thank you so much for contributing to our Repo, Your observation and additions are superb.

Kindly be informed that the BVN issue has been fixed. Kindly make a pull request from our Repo to yours to update it and get the fix.

We look forward to seeing more of your awesome contributions.

Thanks for choosing Flutterwave!

Remain awesome.

**Pull request closed without merging**
